# Generated by Django 6.0.6 on 2026-07-12 18:40

from django.db import migrations, models


def _remove_duplicate_discount_usages(apps, schema_editor):
    DiscountUsage = apps.get_model('discounts', 'DiscountUsage')
    db_alias = schema_editor.connection.alias
    seen = set()
    duplicates = []
    for usage in (
        DiscountUsage.objects.using(db_alias)
        .filter(order__isnull=False)
        .order_by('-created_at')
    ):
        key = (usage.order_id, usage.discount_code_id)
        if key in seen:
            duplicates.append(usage.pk)
        else:
            seen.add(key)
    if duplicates:
        DiscountUsage.objects.using(db_alias).filter(pk__in=duplicates).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_discountusage_status'),
        ('orders', '0006_order_orders_orde_custome_66d5e2_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(
            _remove_duplicate_discount_usages,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='discountusage',
            constraint=models.UniqueConstraint(fields=('order', 'discount_code'), name='unique_order_discount_code'),
        ),
    ]
