services:
  core:
    build:
      context: ./apps/core
    container_name: mugs-core
    ports:
      - "8080:8080"
    env_file:
      - ./apps/core/.env
    volumes:
      - ./apps/core/data.sqlite:/usr/src/app/data.sqlite
      - ./apps/core/storage:/usr/src/app/storage
    networks:
      - mugs
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: mugs-web
    ports:
      - "4321:4321"
    environment:
      - CORE_API_URL=http://core:8080
    depends_on:
      - core
    networks:
      - mugs
    restart: unless-stopped

networks:
  mugs:
    driver: bridge
