packages:
  - 'apps/*'
  - 'packages/*'

overrides:
  yaml: ^2.8.3
  esbuild: ^0.28.1

allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - 'better-sqlite3'
  - 'esbuild'
  - 'sharp'
