# Generated by Django 6.0.6 on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderline',
            name='customer_upload',
            field=models.FileField(blank=True, help_text='Customer drawing to be printed on the mug', null=True, upload_to='drawings/%Y/%m/%d/'),
        ),
    ]
