# Generated by Django 6.0.6 on 2026-07-04 03:19

from django.db import migrations, models


def _existing_columns(schema_editor, table_name):
    """Return a set of column names for the given table."""
    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == 'postgresql':
            cursor.execute(
                "SELECT column_name FROM information_schema.columns WHERE table_name = %s",
                [table_name],
            )
            return {row[0] for row in cursor.fetchall()}
        cursor.execute(f"PRAGMA table_info({table_name})")
        return {row[1] for row in cursor.fetchall()}


def add_processed_upload_columns(apps, schema_editor):
    """Add processed_upload columns idempotently.

    The production PostgreSQL database already has these columns from a
    previous partial migration, so use IF NOT EXISTS there. For other
    backends (e.g. SQLite used in local development) inspect the schema
    and add missing columns manually.
    """
    table_name = 'orders_orderline'
    existing = _existing_columns(schema_editor, table_name)

    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            f"""
            ALTER TABLE {table_name}
            ADD COLUMN IF NOT EXISTS processed_upload varchar(100),
            ADD COLUMN IF NOT EXISTS processed_upload_error text NOT NULL DEFAULT '',
            ADD COLUMN IF NOT EXISTS processed_upload_generated_at timestamp with time zone NULL;
            """
        )
        return

    # Fallback for SQLite and other backends.
    if 'processed_upload' not in existing:
        schema_editor.execute(
            f"ALTER TABLE {table_name} ADD COLUMN processed_upload varchar(100);"
        )
    if 'processed_upload_error' not in existing:
        schema_editor.execute(
            f"ALTER TABLE {table_name} ADD COLUMN processed_upload_error text NOT NULL DEFAULT '';"
        )
    if 'processed_upload_generated_at' not in existing:
        schema_editor.execute(
            f"ALTER TABLE {table_name} ADD COLUMN processed_upload_generated_at timestamp with time zone NULL;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_upload_and_payment_intent'),
    ]

    operations = [
        # The production database already has these columns from a previous
        # partial migration, so make the schema change idempotent.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=add_processed_upload_columns,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='orderline',
                    name='processed_upload',
                    field=models.FileField(blank=True, help_text='AI-cleaned version of the customer drawing ready for Printful', null=True, upload_to='processed/%Y/%m/%d/'),
                ),
                migrations.AddField(
                    model_name='orderline',
                    name='processed_upload_error',
                    field=models.TextField(blank=True),
                ),
                migrations.AddField(
                    model_name='orderline',
                    name='processed_upload_generated_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
    ]
