# Generated by Django 6.0.6 on 2026-06-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_upload_and_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='processed_upload',
            field=models.FileField(blank=True, help_text='AI-processed drawing ready for production', null=True, upload_to='drawings/processed/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processing_ai', 'Processing AI'), ('in_curation', 'In Curation'), ('approved', 'Approved'), ('sent_to_production', 'Sent to Production'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
