# Generated by Django 6.0.6 on 2026-07-04 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('orders', '0005_order_discount_amount_order_discount_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_email', 'status'], name='orders_orde_custome_66d5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['discount_code', 'status'], name='orders_orde_discoun_36a627_idx'),
        ),
    ]
