# Generated by Django 6.0.6 on 2026-07-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_orders_orde_custome_66d5e2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='mockup',
            field=models.FileField(blank=True, help_text='Preview of the customer design applied to the product', null=True, upload_to='mockups/%Y/%m/%d/'),
        ),
    ]
