# Generated by Django 6.0.7 on 2026-07-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderline_mockup'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='processed_upload_prompt',
            field=models.TextField(blank=True, help_text='Operator prompt/instructions used to generate processed_upload'),
        ),
    ]
