# Generated by Django 6.0.7 on 2026-07-19 16:36

import apps.orders.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderline_processed_upload_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='customer_upload',
            field=models.FileField(blank=True, help_text='Customer drawing to be printed on the mug', null=True, storage=apps.orders.storage.customer_upload_storage, upload_to='drawings/%Y/%m/%d/'),
        ),
    ]
