/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as PrintfulIndexRouteImport } from './routes/printful.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as DiscountsIndexRouteImport } from './routes/discounts.index'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as PrintfulWebhooksRouteImport } from './routes/printful.webhooks'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as DiscountsNewRouteImport } from './routes/discounts.new'
import { Route as DiscountsIdRouteImport } from './routes/discounts.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintfulIndexRoute = PrintfulIndexRouteImport.update({
  id: '/printful/',
  path: '/printful/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsIndexRoute = DiscountsIndexRouteImport.update({
  id: '/discounts/',
  path: '/discounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintfulWebhooksRoute = PrintfulWebhooksRouteImport.update({
  id: '/printful/webhooks',
  path: '/printful/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsNewRoute = DiscountsNewRouteImport.update({
  id: '/discounts/new',
  path: '/discounts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsIdRoute = DiscountsIdRouteImport.update({
  id: '/discounts/$id',
  path: '/discounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/discounts/$id': typeof DiscountsIdRoute
  '/discounts/new': typeof DiscountsNewRoute
  '/orders/$id': typeof OrdersIdRoute
  '/printful/webhooks': typeof PrintfulWebhooksRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/new': typeof ProductsNewRoute
  '/discounts/': typeof DiscountsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/printful/': typeof PrintfulIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/discounts/$id': typeof DiscountsIdRoute
  '/discounts/new': typeof DiscountsNewRoute
  '/orders/$id': typeof OrdersIdRoute
  '/printful/webhooks': typeof PrintfulWebhooksRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/new': typeof ProductsNewRoute
  '/discounts': typeof DiscountsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/printful': typeof PrintfulIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/discounts/$id': typeof DiscountsIdRoute
  '/discounts/new': typeof DiscountsNewRoute
  '/orders/$id': typeof OrdersIdRoute
  '/printful/webhooks': typeof PrintfulWebhooksRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/new': typeof ProductsNewRoute
  '/discounts/': typeof DiscountsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/printful/': typeof PrintfulIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/discounts/$id'
    | '/discounts/new'
    | '/orders/$id'
    | '/printful/webhooks'
    | '/products/$id'
    | '/products/new'
    | '/discounts/'
    | '/orders/'
    | '/printful/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/discounts/$id'
    | '/discounts/new'
    | '/orders/$id'
    | '/printful/webhooks'
    | '/products/$id'
    | '/products/new'
    | '/discounts'
    | '/orders'
    | '/printful'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/discounts/$id'
    | '/discounts/new'
    | '/orders/$id'
    | '/printful/webhooks'
    | '/products/$id'
    | '/products/new'
    | '/discounts/'
    | '/orders/'
    | '/printful/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DiscountsIdRoute: typeof DiscountsIdRoute
  DiscountsNewRoute: typeof DiscountsNewRoute
  OrdersIdRoute: typeof OrdersIdRoute
  PrintfulWebhooksRoute: typeof PrintfulWebhooksRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsNewRoute: typeof ProductsNewRoute
  DiscountsIndexRoute: typeof DiscountsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  PrintfulIndexRoute: typeof PrintfulIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printful/': {
      id: '/printful/'
      path: '/printful'
      fullPath: '/printful/'
      preLoaderRoute: typeof PrintfulIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts/': {
      id: '/discounts/'
      path: '/discounts'
      fullPath: '/discounts/'
      preLoaderRoute: typeof DiscountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printful/webhooks': {
      id: '/printful/webhooks'
      path: '/printful/webhooks'
      fullPath: '/printful/webhooks'
      preLoaderRoute: typeof PrintfulWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts/new': {
      id: '/discounts/new'
      path: '/discounts/new'
      fullPath: '/discounts/new'
      preLoaderRoute: typeof DiscountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts/$id': {
      id: '/discounts/$id'
      path: '/discounts/$id'
      fullPath: '/discounts/$id'
      preLoaderRoute: typeof DiscountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DiscountsIdRoute: DiscountsIdRoute,
  DiscountsNewRoute: DiscountsNewRoute,
  OrdersIdRoute: OrdersIdRoute,
  PrintfulWebhooksRoute: PrintfulWebhooksRoute,
  ProductsIdRoute: ProductsIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  DiscountsIndexRoute: DiscountsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  PrintfulIndexRoute: PrintfulIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
