# Generated by Django 6.0.6 on 2026-06-25 05:26

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.product_media_upload_path),
        ),
    ]
