# Generated by Django 6.0.7 on 2026-07-14 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_background',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('transparent', 'Transparent')], default='', help_text='Processed image background (empty = use global default)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='image_format',
            field=models.CharField(blank=True, choices=[('png', 'PNG'), ('jpeg', 'JPEG')], default='', help_text='Output image format (empty = use global default)', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='print_dpi',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Target DPI (0 = use global default)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='print_height_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Print area height in mm (override global default)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='print_width_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Print area width in mm (override global default)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
